<a href="https://colab.research.google.com/github/yjyjy131/Study_Deep_Learning/blob/main/Deep-learning-from-scratch/chapter_4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 편미분 기울기 구하기

In [1]:
import numpy as np

In [51]:
# 편미분이 필요한 수식의 기울기 구하기
def gradient(func, x) :
  h = 1e-4
  grad = np.zeros_like(x)

  for i in range(x.size) :
    tmp_val = x[i]
    x[i] = tmp_val + h
    fxh1 = func(x)

    x[i] = tmp_val - h
    fxh2 = func(x)

    grad[i] = (fxh1 - fxh2) / (2*h)
    x[i] = tmp_val

  return grad

In [52]:
# 서로 다른 변수 x0, x1 을 각각 제곱한 후 더하는 식
def test_func(x) :
  return x[0] ** 2 + x[1] ** 2

In [53]:
# 위 식을 사용하면 정수 배열은 제대로된 결과가 나오지 않는다. 
# 이 넘파이 배열의 dtype 은 int64 형이기 때문에, 위 식의 tmp_val + 1e-4 인 소수 값을 배열에 다시 
# 저장할 때, 소수 그대로의 값이 아닌 정수값으로 변형되어 저장되므로 수식대로의 값을 유지할 수 없다. 
gradient(test_func, np.array([3, 4]))

array([25000, 35000])

In [54]:
gradient(test_func, np.array([3.0, 4.0]))

array([6., 8.])

### 경사 하강법

In [55]:
def gradient_descent(func, init_x, lr, step) :
  x = init_x

  for i in range(step) :
    grad = gradient(func, x)
    x -= lr * grad

  return x

In [57]:
gradient_descent(test_func, np.array([-3.0, 4.0]), 0.01, 1000)

array([-5.04890207e-09,  6.73186943e-09])

In [60]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 

    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

### 신경망과 기울기 

In [62]:
from functions import softmax, cross_entropy_error
from gradient import numerical_gradient

In [103]:
class SimpleNet:
  def __init__(self) :
    self.W = np.random.randn(2, 3)

  def predict(self, x) :
    return np.dot(x, self.W)

  def loss(self, x, y) :
    p = self.predict(x)
    active = softmax(p)
    loss = cross_entropy_error(active, y) 

    return loss


In [104]:
net = SimpleNet()
x = np.array([0.6, 0.9])
p = net.predict(x)

In [105]:
p

array([-0.02395474,  0.94529332, -1.49012425])

In [106]:
y = np.array([0, 0, 1])

In [107]:
def f(W) :
  return net.loss(x, y)

In [110]:
f = lambda w : net.loss(x, y)

In [108]:
#  함수를 간편하게 작성할 수 있어서 다른 함수의 인수로 넣을 때 주로 사용
grad = numerical_gradient(f, net.W)

In [109]:
grad

array([[ 0.15516803,  0.40901696, -0.56418499],
       [ 0.23275204,  0.61352545, -0.84627748]])