<a href="https://colab.research.google.com/github/yjyjy131/Deep-learning-from-scratch/blob/main/chapter_3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 신경망 구현

#### 입력층 → 1층

In [1]:
import numpy as np

In [2]:
x = np.array([1.2, 1.5])
w1 = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
b1 = np.array([0.1, 0.2, 0.3])

In [3]:
a1 = np.dot(x, w1) + b1

In [4]:
a1

array([0.82, 1.19, 1.56])

In [5]:
def sigmoid(x) :
  return 1 / ( 1 + np.exp(-x) )

In [7]:
z1 = sigmoid(a1)

In [8]:
z1

array([0.69423634, 0.76674106, 0.82635335])

#### 1층 → 2층

In [10]:
w2 = np.array([[0.1, 0.3], [0.2, 0.4], [0.1, -0.1]])
b2 = np.array([0.15, 0.13])

a2 = np.dot(z1, w2) + b2
z2 = sigmoid(a2)

In [11]:
z2

array([0.61192407, 0.63699195])

#### 2층 → 출력층

In [12]:
def identity(x) :
  return x

In [13]:
w3 = np.array([[0.1, 0.2],[0.3, 0.4]])
b3 = np.array([0.1, 0.1])

a2 = np.dot(z2, w3) + b3
y = identity(a2)

In [14]:
y

array([0.35228999, 0.47718159])

#### 입력층 → 1층 → 2층 → 출력층

In [15]:
def init_network() :
  # 딕셔너리에 가중치, 편향 저장
  network = {}

  network['w1'] = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['w2'] = np.array([[0.1, 0.3], [0.2, 0.4], [0.1, -0.1]])
  network['b2'] = np.array([0.15, 0.13])
  network['w3'] = np.array([[0.1, 0.2],[0.3, 0.4]])
  network['b3'] = np.array([0.1, 0.1])
  
  return network

In [17]:
# 신경망 순서대로 닷 연산
def forward(network, x) :
  w1, w2, w3 = network['w1'], network['w2'], network['w3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, w1) + b1
  z1 = sigmoid(a1)

  a2 = np.dot(z1, w2) + b2
  z2 = sigmoid(a2)

  a3 = np.dot(z2, w3) + b3
  y = identity(a3)
  
  return y

In [18]:
my_network = init_network()
x = np.array([1, 1])
y = forward(my_network, x)

In [19]:
y

array([0.34960407, 0.47325442])

## softmax 함수 구현

In [20]:
def softmax(x) :
  exp_x = np.exp(x)
  sum_exp = np.sum(x)
  y = exp_x / sum_exp
  
  return y

#### softmax 의 오버플로 방지

In [21]:
def softmax(x) :
  max_v = np.max(x)
  exp_x = np.exp(x - max_v)
  sum_exp = np.sum(exp_x)
  y = exp_x / sum_exp

  return y

In [22]:
a = np.array([0.1, 0.2, 0.3])
softmax(a)

array([0.30060961, 0.33222499, 0.3671654 ])

In [24]:
np.sum(softmax(a))

1.0